### ISSUE TITLE
Support client/server key usages on issued certificates

### ISSUE THREAD

**Issue by kit837** [cert-manager/aws-privateca-issuer#19]
**Usage case:**

I would like to use aws-pca-issuer to issue certificates that can only be used for TLS clients or servers.

**Expected behavior:**

Specify `KeyUsage:  [ "server auth" ]` or `KeyUsage:  [ "client auth" ]` on a certificate resource and be issued a certificate that is limited to those usages.

**Actual behavior:**

KeyUsage on the certificate resource is ignored and a certificate is issued with both client and server key usages.

This is because no `TemplateArn` is specified to `IssueCertificate()` so all certificates use the default `EndEntityCertificate` template which includes both client and server key usages.

**References:**
- [acm-pca - Understanding Certificate Templates](https://docs.aws.amazon.com/acm-pca/latest/userguide/UsingTemplates.html)
- [Existing IssueCertificate() call]( https://github.com/jniebuhr/aws-pca-issuer/blob/667441c3aae7b92e7158f25a7d169ea1230f45b1/pkg/aws/pca.go#L94)
- [cert-manager API reference - KeyUsage](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1alpha2.KeyUsage)

**Comment by kit837** [comment]
I believe cert-manager provides a default already. From [cert-manager - Key Usages](https://cert-manager.io/docs/usage/certificate/#key-usages):
> Unless any number of usages has been set, cert-manager will set the default requested usages of “digital signature”, “key encipherment”, and “server auth”

One other consideration about to `BlankEndEntityCertificate_CSRPassthrough/V1` is that it will not include the `digital signature` and `key encipherment` usages by default. These usages are important to some TLS implementations.

If a user specifies only `KeyUsages: [ "server auth" ]`, they may be surprised when their certificate doesn't work as expected.

**Comment by paramsethi** [comment]
If no templateArn is provided, the acm-pca/IssueCertificate uses default [EndEntityCertificate](https://docs.aws.amazon.com/acm-pca/latest/userguide/UsingTemplates.html#EndEntityCertificate-V1) template which includes both Server, and client auth as keyusage values.

If the KeyUsage in CSR is present, we can use [BlankEndEntityCertificate_CSRPassthrough](https://docs.aws.amazon.com/acm-pca/latest/userguide/UsingTemplates.html#BlankEndEntityCertificate_CSRPassthrough) template.

However, If KeyUsage is not populated in the CSR, we should fall back to using the default [EndEntityCertificate](https://docs.aws.amazon.com/acm-pca/latest/userguide/UsingTemplates.html#EndEntityCertificate-V1) in order to issue a valid X509 certificate.
